import 'package:flutter/material.dart';
import '../../../core/theme/unified_theme.dart';

class AISummaryWidget extends StatelessWidget {
  final String summary;
  final VoidCallback onDismiss;

  const AISummaryWidget({
    super.key,
    required this.summary,
    required this.onDismiss,
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.only(bottom: 20),
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        gradient: LinearGradient(
          colors: [
            UnifiedTheme.blueAccent.withOpacity(0.1),
            UnifiedTheme.blueAccent.withOpacity(0.05),
          ],
        ),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: UnifiedTheme.blueAccent.withOpacity(0.3)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Container(
                padding: const EdgeInsets.all(6),
                decoration: BoxDecoration(
                  color: UnifiedTheme.blueAccent,
                  borderRadius: BorderRadius.circular(6),
                ),
                child: const Icon(
                  Icons.auto_awesome,
                  color: Colors.white,
                  size: 16,
                ),
              ),
              const SizedBox(width: 8),
              const Text(
                'AI Summary',
                style: TextStyle(
                  fontSize: 14,
                  fontWeight: FontWeight.w600,
                  color: UnifiedTheme.primaryText,
                ),
              ),
              const Spacer(),
              IconButton(
                onPressed: onDismiss,
                icon: const Icon(Icons.close),
                iconSize: 16,
                color: UnifiedTheme.tertiaryText,
                padding: EdgeInsets.zero,
                constraints: const BoxConstraints(
                  minWidth: 24,
                  minHeight: 24,
                ),
              ),
            ],
          ),
          const SizedBox(height: 12),
          Text(
            summary,
            style: const TextStyle(
              fontSize: 14,
              color: UnifiedTheme.secondaryText,
              height: 1.5,
            ),
          ),
          const SizedBox(height: 12),
          Row(
            children: [
              const Icon(
                Icons.lightbulb_outline,
                size: 14,
                color: UnifiedTheme.tertiaryText,
              ),
              const SizedBox(width: 4),
              Text(
                'Generated by AI',
                style: TextStyle(
                  fontSize: 12,
                  color: UnifiedTheme.tertiaryText,
                  fontStyle: FontStyle.italic,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}