// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0a-BV19LHbyH18F1SaZ8DlNNnEykziWs',
    appId: '1:116294954906:web:1f88ab845d2baaf2f5d423',
    messagingSenderId: '116294954906',
    projectId: 'vet-pathshala',
    authDomain: 'vet-pathshala.firebaseapp.com',
    databaseURL: 'https://vet-pathshala-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vet-pathshala.firebasestorage.app',
    measurementId: 'G-NVHK9JSDCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlJlzuELWLJ2N7fL0OlBsjfk-KR_MmvkM',
    appId: '1:116294954906:android:128826c99672d1d6f5d423',
    messagingSenderId: '116294954906',
    projectId: 'vet-pathshala',
    authDomain: 'vet-pathshala.firebaseapp.com',
    databaseURL: 'https://vet-pathshala-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vet-pathshala.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0a-BV19LHbyH18F1SaZ8DlNNnEykziWs',
    appId: '1:116294954906:ios:128826c99672d1d6f5d423',
    messagingSenderId: '116294954906',
    projectId: 'vet-pathshala',
    authDomain: 'vet-pathshala.firebaseapp.com',
    databaseURL: 'https://vet-pathshala-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vet-pathshala.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0a-BV19LHbyH18F1SaZ8DlNNnEykziWs',
    appId: '1:116294954906:ios:128826c99672d1d6f5d423',
    messagingSenderId: '116294954906',
    projectId: 'vet-pathshala',
    authDomain: 'vet-pathshala.firebaseapp.com',
    databaseURL: 'https://vet-pathshala-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vet-pathshala.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0a-BV19LHbyH18F1SaZ8DlNNnEykziWs',
    appId: '1:116294954906:web:1f88ab845d2baaf2f5d423',
    messagingSenderId: '116294954906',
    projectId: 'vet-pathshala',
    authDomain: 'vet-pathshala.firebaseapp.com',
    databaseURL: 'https://vet-pathshala-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vet-pathshala.firebasestorage.app',
    measurementId: 'G-NVHK9JSDCQ',
  );
}